### ISSUE TITLE
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by idubrov** [cellog/react-redux-saga-router#5]
I am getting the following error:
```Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.```

if I have multiple ```<Route>``` inside ```<Routes>``` component. This might be due to ```React.cloneElement``` inside ```Routes.jsx``` (see http://stackoverflow.com/questions/38011702/how-to-clone-multiple-children-with-react-cloneelement).

**Comment by cellog** [comment]
Hi,

Can you provide a snippet of react code showing what you mean?




I can use it for a unit test to fix this.
Thanks!

**Comment by idubrov** [comment]
Sorry I cannot provide the whole example, but essentially what I am doing is:

    <App>
       <Routes />
       ...
    </App>

Where Routes is:
    
    export default () => (
      <Routes>
        <Route name="home" path="/" />
        <Route name="first" path="/first" />
      </Routes>
    );

It fails with the error I mentioned above. However, if I remove one Route, it works fine (i.e, Routes cannot handle more than one Route as a children).

(I use React 15.4.2, don't know if that matters...)

**Comment by cellog** [comment]
Oh OK. I will take a look

**Comment by cellog** [comment]
I'm away from a computer for a few hours, but your analysis seems correct. Will be an easy fix, I just need to create a failing test and then I will release the fix 

For a stopgap, you can also define routes using a map that has the same keys as the props passed to `<Route>` and pass that into the route initializer (the function you import from react-redux-saga-router to pass in the saga Middleware and react-redux connect). You can also use multiple `<Routes>` tags as a stopgap until I fix this later today. Let me know if you have any trouble with the stopgaps!

**Comment by cellog** [comment]
That fix works, I will commit as soon I get to wifi and release 0.4.0

**Comment by cellog** [comment]
0.4.0 just released with this fix.  Please re-open if the problem persists
